### ISSUE TITLE
sep_by fails with composed parser

### ISSUE THREAD

**Issue by cedriessen** [bitwalker/combine#35]
Using `sep_by` with a simple parser works fine...
```elixir
test "sep_by with single parser (passes)" do
  multiple = sep_by(string("txt"), char(","))
  assert [["txt", "txt"]] == Combine.parse("txt,txt", multiple)
end
```
... but using it with a composed parser fails with an exception. Am I missing something?

```elixir
test "sep_by with parser composition (fails)" do
  composed_parser = string("txt") |> string("2")
  multiple = sep_by(composed_parser, char(","))
  assert [[["txt", "2"], ["txt", "2"]]] == Combine.parse("txt2,txt2", multiple)
end
```

```
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Combine.Parsers.Base.pair_right_impl/3
     stacktrace:
       (combine) lib/combine/parsers/base.ex:234: anonymous fn([",", "txt", "2"]) in Combine.Parsers.Base.pair_right_impl/3
       (combine) lib/combine/parsers/base.ex:154: Combine.Parsers.Base.pipe_impl/3
       (combine) lib/combine/parsers/base.ex:315: Combine.Parsers.Base.many1_impl/2
       (combine) lib/combine/parsers/base.ex:347: Combine.Parsers.Base.many_impl/2
       (combine) lib/combine/parsers/base.ex:163: Combine.Parsers.Base.do_pipe/3
       (combine) lib/combine/parsers/base.ex:152: Combine.Parsers.Base.pipe_impl/3
       (combine) lib/combine/parsers/base.ex:385: Combine.Parsers.Base.sep_by_impl/3
       (combine) lib/combine.ex:52: Combine.parse/2
```

**Comment by cedriessen** [comment]
I think I got it: To compose multiple parsers into one the `pipe` function is the way to go.

```elixir
test "sep_by with parser composition (fails)" do
  composed_parser = pipe([string("txt"), string("2")], fn x -> x end)
  multiple = sep_by(composed_parser, char(","))
  assert [[["txt", "2"], ["txt", "2"]]] == Combine.parse("txt2,txt2", multiple)
end
```
